routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/','Frontend\HomeController@index');
Route::get('/member','Frontend\HomeController@ourteam');
Route::get('/about','Frontend\HomeController@about');
Route::get('/eminent-education','Frontend\HomeController@eminentedu');
Route::get('/biotech-usa','Frontend\HomeController@biotech');
Route::get('/uk-uni','Frontend\HomeController@ukuni');






Route::group(['prefix'=>'admin' ,'as' => 'admin.','middleware'=>'auth'],function() {
    Route::get('/', 'admin\AdminController@dashboard')->name('dashboard');
    Route::resource('/slider', 'admin\SliderController');
    Route::resource('/program', 'admin\ProgramController');


});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Slider;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $sliders=Slider::where('status',1)->get();
        return view('backend.slider.index')
            ->with('sliders',$sliders);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());
        $slider = Slider::create(Input::all());
        if (Input::hasFile('image'))
        {
            $image= Input::file('image');
            $imageName=Str::random('32').'.'.$image->getClientOriginalExtension();
            $image->move('public/images/slider/',$imageName);
            $slider->image=$imageName;
        }
        $slider->save();
        return redirect('admin/slider');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sliders=Slider::where('status',1)->first();
        return view('backend.slider.edit')
            ->with('sliders',$sliders);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider=Slider::find($id);
        $slider->title=Input::get('title');
        $slider->heading=Input::get('heading');
        $slider->description=Input::get('description');
        $slider->status=Input::get('status');
        if (Input::hasFile('image'))
        {
            $image= Input::file('image');
            $imageName=Str::random('32').'.'.$image->getClientOriginalExtension();
            $image->move('public/images/slider/',$imageName);
            $slider->image=$imageName;
        }
        $slider->save();
        return redirect('admin/slider');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider=Slider::find($id);
        $slider->delete();
        return redirect('admin/slider');
    }
}

resources/views/backend/slider/create.blade.php
@extends('backend.baselayout');
@section('admin-section')

        <div class="row">
            <h3> Create Sliders</h3>
        </div>
            <div class="col-md-8">

                <form method="post" action="{{ route('admin.slider.store') }}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label class="control-label" for="inputSuccess">Title</label>
                        <input type="text" class="form-control" name="title">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSuccess">Heading</label>
                        <input type="text" class="form-control" name="heading">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSuccess">Description</label>
                        <textarea name="description" rows="7" cols="50" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                         <label class="control-label" for="inputSuccess">Choose</label>
                        <input type="file" name="image" class="form-control">
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="inputSuccess">Choose Status</label>
                            <select class="form-control" name="status">
                                <option value="1">Active</option>
                                <option value="0'">Inactive</option>
                            </select>
                    </div>
                    <br>
                    <p><input type="submit" name="submit" class="btn btn-primary"/></p>

                </form>
            </div>

    @endsection

resources/views/backend/slider/edit.blade.php
@extends('backend.baselayout');
@section('admin-section')

    <div class="row">
        <h3> Edit Sliders</h3>
    </div>
    <div class="col-md-8">

        <form method="post" action="{{ url('admin/slider/'.$sliders->id) }}" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
            <input type="hidden" name="_method" value="PATCH">
            <div class="form-group">
                <label class="control-label" for="inputSuccess">Title</label>
                <input type="text" class="form-control" value="{{ $sliders->title }}" name="title">
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess">Heading</label>
                <input type="text" class="form-control" value="{{ $sliders->heading }}" name="heading">
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess">Description</label>
                <textarea name="description" rows="7" cols="50" class="form-control">
                    {{ $sliders->description }}
                </textarea>
            </div>
            <div class="form-group">
                <label class="control-label" for="inputSuccess">Choose</label>
                <input type="file" name="image" class="form-control">
            </div>

            <div class="form-group">
                <label class="control-label" for="inputSuccess">Choose Status</label>
                <select class="form-control" name="status">
                    <option value="1">Active</option>
                    <option value="0'">Inactive</option>
                </select>
            </div>
            <br>
            <p><input type="submit" name="submit" class="btn btn-primary"/></p>

        </form>
    </div>

@endsection

resources/views/backend/slider/index.blade.php
@extends('backend.baselayout');
@section('admin-section')
    <div class="row">
        <h3> List of Sliders</h3>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        DataTables Advanced Tables
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Title</th>
                                    <th>Heading</th>
                                    <th>Descripton</th>
                                    <th>Image</th>
                                    <th>Status</th>
                                    <th>Action(s)</th>

                                </tr>
                                </thead>
                                <tbody>

                                @foreach($sliders as $slider)
                                    <tr>
                                        <td>1</td>
                                        <td>{{ $slider->title }}</td>
                                        <td> {{ $slider->heading }}</td>
                                        <td>{!! $slider->description !!}</td>
                                        <td></td>
                                        <td>
                                            {{ $slider->status==1?"active":"inactive" }}</td>
                                        <td>
                                            <a href="{{ url('admin/slider/'.$slider->id.'/edit') }}"><button type="button" class="btn btn-primary"> <span class="fa fa-edit"></span> </button></a>
                                            <form action="{{ url('admin/slider/'.$slider->id) }}" method="POST">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="hidden" name="_method" value="Delete">
                                                <input type="submit" class="btn btn-danger" value="Delete" onclick="return confirm('Are you sure to Delete')">

                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>




    </div>
@endsection